[package]
name = "jingle"
version = "0.1.1"
edition = "2021"
description = "SMT Modeling for Ghidra's PCODE"
homepage = "https://github.com/toolCHAINZ/jingle"
repository = "https://github.com/toolCHAINZ/jingle"
readme = "README.md"
license = "MIT"
authors = ["toolCHAINZ"]
rust-version = "1.77.0"
categories = ["mathematics"]
keywords = ["ghidra", "sleigh", "pcode", "smt"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jingle_sleigh = { path = "../jingle_sleigh", version = "0.1.1" }
z3 = { git = "https://github.com/prove-rs/z3.rs.git", rev = "1971033" }
thiserror = "1.0.58"
serde = { version = "1.0.197", features = ["derive"] }
tracing = "0.1.40"

[features]
elf = ["jingle_sleigh/elf"]
gimli = ["jingle_sleigh/gimli"]
